# _data/visiting.yaml
html: |
    <ul>
        <li>Reviewer of NeurIPS (2025)</li>
        <li>Reviewer of IEEE Transactions on Signal Processing</li>
        <li>Reviewer of IEEE Transactions on Signal and Information Processing over Networks</li>
        <li>Reviewer of IEEE Transactions on Automatic Control</li>
        <li>Reviewer of IEEE Transactions on Circuits and Systems for Video Technology</li>
        <li>Reviewer of IEEE Transactions on Neural Networks and Learning Systems</li>
        <li>Reviewer of IEEE Transactions on Information Forensics and Security</li>
        <li>Reviewer of Signal Processing</li>
        <li>Reviewer of IEEE International Symposium on Information Theory</li>
        <li>Reviewer of American Control Conference</li>
    </ul>